org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

minecraft_version=1.20.4

banner_sections_versions=1.20.4
forge_version_1.18.2=40.3.11
forge_version_1.19.2=43.5.2
forge_version_1.19.4=45.4.3
forge_version_1.20.1=47.3.7
forge_version_1.20.4=49.1.4

mod_id=mtrfranceaddon
mod_name=MTR France Addon
mod_version=2.0.0-alpha.1
maven_group=fr.adlmrl
archives_base_name=MTRFRA

mtr_version=4.0.5
mtr_version_range=[4.0.4,4.1)
forge_loader_range_1.18.2=[40,)
forge_loader_range_1.19.2=[43,)
forge_loader_range_1.19.4=[45,)
forge_loader_range_1.20.1=[47,)
forge_loader_range_1.20.4=[49,)
pack_format_1.18.2=8
pack_format_1.19.2=9
pack_format_1.19.4=13
pack_format_1.20.1=15
pack_format_1.20.4=22
